sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: xhjj0521

  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: "YOUR_ACCESS_KEY_ID"      # 改成这个，不要留真实值
    access-key-secret: "YOUR_ACCESS_KEY_SECRET" # 改成这个，不要留真实值
    bucket-name: verstappen
 