sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: xhjj0521

  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tBE9WStUDvdUvhhEDHP
    access-key-secret: bkSH1tfGyja6BCj60FyyvuKuoY20pc
    bucket-name: verstappen
 